# Generated by Django 2.2.2 on 2019-07-04 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=100)),
                ('course_credit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('teacher_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='session',
            fields=[
                ('batch', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('running', models.BooleanField(default=True)),
                ('course_code', models.ForeignKey(default='def_course', on_delete=django.db.models.deletion.SET_DEFAULT, to='teacher.course')),
                ('teacher_code', models.ForeignKey(default='no_teach', on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_code',
            field=models.ForeignKey(default='NoTea', on_delete=django.db.models.deletion.SET_DEFAULT, to='teacher.teacher'),
        ),
    ]
