# Generated by Django 2.2.2 on 2019-07-04 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='course_code',
            field=models.ForeignKey(default='def_cor', on_delete=django.db.models.deletion.SET_DEFAULT, to='teacher.course'),
        ),
        migrations.AlterField(
            model_name='session',
            name='teacher_code',
            field=models.ForeignKey(default='notea', on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
