# Generated by Django 2.2.2 on 2019-07-01 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_course_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='course_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.course'),
        ),
    ]
