# Generated by Django 2.2.2 on 2019-07-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20190702_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='batch',
            field=models.CharField(max_length=4),
        ),
    ]
