# Generated by Django 2.2.2 on 2019-07-04 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('reg_number', models.CharField(default='000', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=300)),
                ('group_name', models.CharField(max_length=100)),
                ('course_code', models.ForeignKey(default=111, on_delete=django.db.models.deletion.SET_DEFAULT, to='teacher.course', verbose_name='course')),
                ('member1_reg', models.ForeignKey(default='mem1', on_delete=django.db.models.deletion.CASCADE, related_name='member1', to='student.student')),
                ('member2_reg', models.ForeignKey(default='mem2', on_delete=django.db.models.deletion.CASCADE, related_name='member2', to='student.student')),
                ('member3_reg', models.ForeignKey(default='mem3', on_delete=django.db.models.deletion.CASCADE, related_name='member3', to='student.student')),
                ('session', models.ForeignKey(default=222, on_delete=django.db.models.deletion.SET_DEFAULT, to='teacher.session', verbose_name='session')),
            ],
        ),
    ]
