# Generated by Django 2.2.2 on 2019-07-01 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20190702_0340'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=300)),
                ('group_name', models.CharField(max_length=100)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.course')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.session')),
            ],
        ),
    ]
