# Generated by Django 2.2.3 on 2019-07-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.CharField(default='pid', max_length=100, primary_key=True, serialize=False),
        ),
    ]
